// NSW Science Curriculum Units - extracted from Scope and Sequence documents

export interface CurriculumUnit {
  id: string;
  stage: string; // "Early Stage 1", "Stage 1", etc.
  component?: string; // For Life Skills: "Component A", "Component B", etc.
  term: number; // 1-4
  name: string;
  description: string;
  outcomes: string[]; // e.g., ["SCLS-WS-01", "SCLS-WS-03"]
  weeks: number; // typically 8
}

// K-6 Science and Technology Units
export const k6Units: CurriculumUnit[] = [
  // Early Stage 1
  {
    id: "es1-t1",
    stage: "Early Stage 1",
    term: 1,
    name: "Living things have characteristics that help them survive in their environment",
    description: "Identify the sense organs and describe their functions. Identify and use tools to aid and extend sensory observations. Describe how living things get air, water and energy to survive in their environment.",
    outcomes: ["STE-SCI-01", "STE-PQU-01"],
    weeks: 8,
  },
  {
    id: "es1-t2",
    stage: "Early Stage 1",
    term: 2,
    name: "Objects are made of materials that have observable properties",
    description: "Recognise that properties of materials can be observed using the senses. Observe and manipulate materials to describe their properties. Explore how Aboriginal and/or Torres Strait Islander Peoples use natural materials for specific purposes.",
    outcomes: ["STE-SCI-01", "STE-PQU-01", "STE-DDT-01"],
    weeks: 8,
  },
  {
    id: "es1-t3",
    stage: "Early Stage 1",
    term: 3,
    name: "Understanding user needs inspires design and digital solutions",
    description: "Design and build a simple product that addresses a user need or opportunity. Examine designed structures that animals build to help them survive in their environment.",
    outcomes: ["STE-DDT-01", "STE-PQU-01"],
    weeks: 8,
  },
  {
    id: "es1-t4",
    stage: "Early Stage 1",
    term: 4,
    name: "Living things and objects move in different ways",
    description: "Observe, describe and categorise the ways in which living things move. Test how the movement of an object is affected by its shape and material.",
    outcomes: ["STE-SCI-01", "STE-PQU-01"],
    weeks: 8,
  },
  
  // Stage 1 (8 terms across 2 years)
  {
    id: "s1-t1",
    stage: "Stage 1",
    term: 1,
    name: "Living things change over time",
    description: "Collect data about the variety of living things in a local habitat. Describe the changes in a plant and animal as they go through their life cycles using data and scientific models.",
    outcomes: ["ST1-SCI-01", "ST1-PQU-01", "ST1-DAT-01"],
    weeks: 8,
  },
  {
    id: "s1-t2",
    stage: "Stage 1",
    term: 2,
    name: "A design process is used to define user needs and create solutions",
    description: "Recognise that a design process breaks large projects into manageable steps. Test how materials with different properties contribute to the effectiveness of a product.",
    outcomes: ["ST1-DDT-01", "ST1-PQU-01"],
    weeks: 8,
  },
  {
    id: "s1-t3",
    stage: "Stage 1",
    term: 3,
    name: "Planet Earth is our home",
    description: "Observe and record daily weather to identify changes and patterns. Investigate how seasonal patterns influence the behaviour and appearance of living things.",
    outcomes: ["ST1-SCI-01", "ST1-PQU-01", "ST1-DAT-01"],
    weeks: 8,
  },
  {
    id: "s1-t4",
    stage: "Stage 1",
    term: 4,
    name: "The human body's sense organs detect its environment",
    description: "Investigate how the human senses detect the environment. Explore how sense organs help us interact with the world around us.",
    outcomes: ["ST1-SCI-01", "ST1-PQU-01"],
    weeks: 8,
  },
  {
    id: "s1-t5",
    stage: "Stage 1",
    term: 5,
    name: "Light and sound interact with materials in different ways",
    description: "Investigate how light and sound interact with different materials. Explore reflection, absorption, and transmission of light and sound.",
    outcomes: ["ST1-SCI-01", "ST1-PQU-01"],
    weeks: 8,
  },
  {
    id: "s1-t6",
    stage: "Stage 1",
    term: 6,
    name: "Light and sound interact with materials in different ways",
    description: "Continue investigating how light and sound interact with different materials. Explore reflection, absorption, and transmission of light and sound.",
    outcomes: ["ST1-SCI-01", "ST1-PQU-01"],
    weeks: 8,
  },
  {
    id: "s1-t7",
    stage: "Stage 1",
    term: 7,
    name: "The sky is our window to the Universe",
    description: "Observe and describe patterns in the sky. Explore the sun, moon, and stars and their movements across the sky.",
    outcomes: ["ST1-SCI-01", "ST1-PQU-01"],
    weeks: 8,
  },
  {
    id: "s1-t8",
    stage: "Stage 1",
    term: 8,
    name: "Forces can change the way objects move",
    description: "Investigate how forces affect the movement of objects. Explore pushing, pulling, and the effects of friction on motion.",
    outcomes: ["ST1-SCI-01", "ST1-PQU-01"],
    weeks: 8,
  },
  
  // Stage 2 (8 terms across 2 years)
  {
    id: "s2-t1",
    stage: "Stage 2",
    term: 1,
    name: "Living things depend on energy and materials to survive",
    description: "Describe the energy and materials that plants and animals need to survive. Investigate how living things obtain their food and energy.",
    outcomes: ["ST2-SCI-01", "ST2-PQU-01"],
    weeks: 8,
  },
  {
    id: "s2-t2",
    stage: "Stage 2",
    term: 2,
    name: "Design is a process of creating and innovating",
    description: "Apply design thinking to create innovative solutions. Test and evaluate products and systems to meet user needs.",
    outcomes: ["ST2-DDT-01", "ST2-PQU-01"],
    weeks: 8,
  },
  {
    id: "s2-t3",
    stage: "Stage 2",
    term: 3,
    name: "Forces shape Earth's surface",
    description: "Investigate how forces shape Earth's surface through weathering and erosion. Describe how natural events and human activity can change the Earth's surface.",
    outcomes: ["ST2-SCI-01", "ST2-PQU-01"],
    weeks: 8,
  },
  {
    id: "s2-t4",
    stage: "Stage 2",
    term: 4,
    name: "Body systems work together to enable movement",
    description: "Investigate how the skeletal and muscular systems work together. Explore how the body coordinates movement and maintains balance.",
    outcomes: ["ST2-SCI-01", "ST2-PQU-01"],
    weeks: 8,
  },
  {
    id: "s2-t5",
    stage: "Stage 2",
    term: 5,
    name: "The Sun is the centre of our solar system and provides our world with energy",
    description: "Investigate the role of the Sun in our solar system. Explore how the Sun provides energy for Earth and drives weather patterns.",
    outcomes: ["ST2-SCI-01", "ST2-PQU-01"],
    weeks: 8,
  },
  {
    id: "s2-t6",
    stage: "Stage 2",
    term: 6,
    name: "Design is a process of creating and innovating",
    description: "Continue applying design thinking to create innovative solutions. Test and evaluate products and systems to meet user needs.",
    outcomes: ["ST2-DDT-01", "ST2-PQU-01"],
    weeks: 8,
  },
  {
    id: "s2-t7",
    stage: "Stage 2",
    term: 7,
    name: "Energy is required to change the properties of matter",
    description: "Investigate how energy changes the properties of matter. Explore heating, cooling, and state changes in materials.",
    outcomes: ["ST2-SCI-01", "ST2-PQU-01"],
    weeks: 8,
  },
  {
    id: "s2-t8",
    stage: "Stage 2",
    term: 8,
    name: "Heat energy can be transferred",
    description: "Investigate how heat energy is transferred through conduction, convection, and radiation. Explore thermal insulators and conductors.",
    outcomes: ["ST2-SCI-01", "ST2-PQU-01"],
    weeks: 8,
  },
  
  // Stage 3 (8 terms across 2 years)
  {
    id: "s3-t1",
    stage: "Stage 3",
    term: 1,
    name: "Earth's climate is affected by natural and human activities",
    description: "Investigate how Earth's climate is changing and the role of human activities. Explore sustainable practices to address climate change.",
    outcomes: ["ST3-SCI-01", "ST3-PQU-01", "ST3-DAT-01"],
    weeks: 8,
  },
  {
    id: "s3-t2",
    stage: "Stage 3",
    term: 2,
    name: "Body systems coordinate for survival",
    description: "Investigate how different body systems work together. Explore the circulatory, respiratory, and digestive systems and their coordination.",
    outcomes: ["ST3-SCI-01", "ST3-PQU-01"],
    weeks: 8,
  },
  {
    id: "s3-t3",
    stage: "Stage 3",
    term: 3,
    name: "Electrical energy can be transferred and transformed",
    description: "Investigate how electrical energy can be transferred and transformed in circuits. Design and construct simple circuits and test their effectiveness.",
    outcomes: ["ST3-SCI-01", "ST3-PQU-01"],
    weeks: 8,
  },
  {
    id: "s3-t4",
    stage: "Stage 3",
    term: 4,
    name: "Electrical energy can be transferred and transformed",
    description: "Continue investigating how electrical energy can be transferred and transformed in circuits. Design more complex circuits.",
    outcomes: ["ST3-SCI-01", "ST3-PQU-01"],
    weeks: 8,
  },
  {
    id: "s3-t5",
    stage: "Stage 3",
    term: 5,
    name: "Living things may change over millions of years, in response to their environments",
    description: "Investigate how living things adapt and evolve over time. Explore fossils and evidence of change in living things.",
    outcomes: ["ST3-SCI-01", "ST3-PQU-01", "ST3-DAT-01"],
    weeks: 8,
  },
  {
    id: "s3-t6",
    stage: "Stage 3",
    term: 6,
    name: "A fixed amount of usable matter makes up all the material on Earth",
    description: "Investigate the water cycle and matter cycles. Explore how matter is conserved and recycled in natural systems.",
    outcomes: ["ST3-SCI-01", "ST3-PQU-01"],
    weeks: 8,
  },
  {
    id: "s3-t7",
    stage: "Stage 3",
    term: 7,
    name: "Our solar system is a part of one of billions of galaxies in the Universe",
    description: "Investigate our solar system and its place in the Universe. Explore the scale of the Universe and Earth's place within it.",
    outcomes: ["ST3-SCI-01", "ST3-PQU-01"],
    weeks: 8,
  },
  {
    id: "s3-t8",
    stage: "Stage 3",
    term: 8,
    name: "Design processes explore opportunities and develop solutions",
    description: "Apply comprehensive design processes to identify opportunities and develop innovative solutions. Evaluate and refine designs.",
    outcomes: ["ST3-DDT-01", "ST3-PQU-01"],
    weeks: 8,
  },
];

// 7-12 Science Life Skills Units
export const lifeSkillsUnits: CurriculumUnit[] = [
  // Component A (Year 7)
  {
    id: "comp-a-t1",
    stage: "7-10 Life Skills",
    component: "Component A",
    term: 1,
    name: "Scientific Senses",
    description: "Students will use their senses and simple tools to make observations and participate in simple, safe investigations.",
    outcomes: ["SCLS-WS-01", "SCLS-WS-03", "SCLS-WS-04", "SCLS-WS-05"],
    weeks: 8,
  },
  {
    id: "comp-a-t2",
    stage: "7-10 Life Skills",
    component: "Component A",
    term: 2,
    name: "Living and Non-Living",
    description: "Students will identify the characteristics of living and non-living things in their environment and describe ways to help them survive.",
    outcomes: ["SCLS-FNS-01", "SCLS-FNS-02"],
    weeks: 8,
  },
  {
    id: "comp-a-t3",
    stage: "7-10 Life Skills",
    component: "Component A",
    term: 3,
    name: "Simple Machines",
    description: "Students will recognize the forces and motion of objects in everyday contexts, such as pushing and pulling things.",
    outcomes: ["SCLS-FOR-01", "SCLS-WAM-01"],
    weeks: 8,
  },
  {
    id: "comp-a-t4",
    stage: "7-10 Life Skills",
    component: "Component A",
    term: 4,
    name: "Matter Around Us",
    description: "Students will describe the properties of familiar substances and materials and observe simple chemical changes.",
    outcomes: ["SCLS-SOL-01", "SCLS-CHG-01"],
    weeks: 8,
  },
  
  // Component B (Year 8)
  {
    id: "comp-b-t1",
    stage: "7-10 Life Skills",
    component: "Component B",
    term: 1,
    name: "Asking Questions",
    description: "Students will ask questions and make predictions based on their observations and communicate their ideas.",
    outcomes: ["SCLS-WS-02", "SCLS-WS-08", "SCLS6-1"],
    weeks: 8,
  },
  {
    id: "comp-b-t2",
    stage: "7-10 Life Skills",
    component: "Component B",
    term: 2,
    name: "Weather and Climate",
    description: "Students will collect and interpret data about local weather patterns and communicate their findings.",
    outcomes: ["SCLS-WS-06", "SCLS-WS-08", "SCLS6-4"],
    weeks: 8,
  },
  {
    id: "comp-b-t3",
    stage: "7-10 Life Skills",
    component: "Component B",
    term: 3,
    name: "Using Resources Wisely",
    description: "Students will manage personal resources and contribute to sustainable practices in their community.",
    outcomes: ["SCLS-RES-01", "SCLS-RES-02"],
    weeks: 8,
  },
  {
    id: "comp-b-t4",
    stage: "7-10 Life Skills",
    component: "Component B",
    term: 4,
    name: "Our Solar System",
    description: "Students will make observations about the sun, moon, and stars, and communicate their understanding of the Universe.",
    outcomes: ["SCLS-OTU-01", "SCLS-WS-08"],
    weeks: 8,
  },
  
  // Component C (Year 9)
  {
    id: "comp-c-t1",
    stage: "7-10 Life Skills",
    component: "Component C",
    term: 1,
    name: "Investigating Health",
    description: "Students will plan and participate in investigations to collect data about healthy practices and disease prevention.",
    outcomes: ["SCLS-WS-03", "SCLS-WS-04", "SCLS-DIS-01", "SCLS6-2"],
    weeks: 8,
  },
  {
    id: "comp-c-t2",
    stage: "7-10 Life Skills",
    component: "Component C",
    term: 2,
    name: "Our Food",
    description: "Students will explore the properties of familiar substances, including food, and learn about the chemical changes that occur when cooking.",
    outcomes: ["SCLS-SOL-01", "SCLS-CHG-01", "SCLS-RXN-01"],
    weeks: 8,
  },
  {
    id: "comp-c-t3",
    stage: "7-10 Life Skills",
    component: "Component C",
    term: 3,
    name: "Energy in Our Lives",
    description: "Students will describe how energy is used in familiar contexts and explore how waves transfer energy.",
    outcomes: ["SCLS-EGU-01", "SCLS-WAM-01"],
    weeks: 8,
  },
  {
    id: "comp-c-t4",
    stage: "7-10 Life Skills",
    component: "Component C",
    term: 4,
    name: "Ecosystems",
    description: "Students will describe ways to sustain living things in an ecosystem and solve problems related to environmental changes.",
    outcomes: ["SCLS-FNS-02", "SCLS-WS-07", "SCLS-RES-02"],
    weeks: 8,
  },
  
  // Component D (Year 10)
  {
    id: "comp-d-t1",
    stage: "7-10 Life Skills",
    component: "Component D",
    term: 1,
    name: "Planning Investigations",
    description: "Students will plan and participate in investigations to obtain both primary and secondary data, focusing on safe practices.",
    outcomes: ["SCLS-WS-03", "SCLS-WS-04", "SCLS6-2", "SCLS6-3"],
    weeks: 8,
  },
  {
    id: "comp-d-t2",
    stage: "7-10 Life Skills",
    component: "Component D",
    term: 2,
    name: "Data and Evidence",
    description: "Students will use data and evidence from scientific investigations to draw conclusions and make informed decisions.",
    outcomes: ["SCLS-WS-06", "SCLS-DAS-01", "SCLS6-8", "SCLS6-9"],
    weeks: 8,
  },
  {
    id: "comp-d-t3",
    stage: "7-10 Life Skills",
    component: "Component D",
    term: 3,
    name: "Chemical Reactions",
    description: "Students will observe and describe a variety of chemical reactions and geological changes in the world around them.",
    outcomes: ["SCLS-CHG-01", "SCLS-RXN-01", "SCLS6-10"],
    weeks: 8,
  },
  {
    id: "comp-d-t4",
    stage: "7-10 Life Skills",
    component: "Component D",
    term: 4,
    name: "Genetic Traits",
    description: "Students will identify their own personal genetic traits and explore how they are passed on.",
    outcomes: ["SCLS-GEV-01", "SCLS6-10"],
    weeks: 8,
  },
  
  // Component E (Year 11)
  {
    id: "comp-e-t1",
    stage: "11-12 Science Life Skills",
    component: "Component E",
    term: 1,
    name: "Solving Scientific Problems",
    description: "Students will identify scientific problems and develop strategies to solve them, using data and evidence.",
    outcomes: ["SCLS-WS-07", "SCLS-DAS-01", "SCLS6-6", "SCLS6-8"],
    weeks: 8,
  },
  {
    id: "comp-e-t2",
    stage: "11-12 Science Life Skills",
    component: "Component E",
    term: 2,
    name: "Understanding Our Universe",
    description: "Students will explore models and descriptions of astronomical phenomena and communicate scientific information about the universe.",
    outcomes: ["SCLS-OTU-01", "SCLS-WS-08", "SCLS6-10"],
    weeks: 8,
  },
  {
    id: "comp-e-t3",
    stage: "11-12 Science Life Skills",
    component: "Component E",
    term: 3,
    name: "Forces and Motion",
    description: "Students will describe the motion of objects and waves, and explore how forces affect them in different situations.",
    outcomes: ["SCLS-FOR-01", "SCLS-WAM-01", "SCLS6-10"],
    weeks: 8,
  },
  {
    id: "comp-e-t4",
    stage: "11-12 Science Life Skills",
    component: "Component E",
    term: 4,
    name: "Healthy Habits for All",
    description: "Students will develop solutions for a range of health concepts and communicate scientific information about disease prevention.",
    outcomes: ["SCLS-DIS-01", "SCLS-RES-01", "SCLS6-7"],
    weeks: 8,
  },
  
  // Component F (Year 12)
  {
    id: "comp-f-t1",
    stage: "11-12 Science Life Skills",
    component: "Component F",
    term: 1,
    name: "Scientific Communication",
    description: "Students will develop and communicate questions and conclusions about a scientific investigation using scientific language and terminology.",
    outcomes: ["SCLS-WS-02", "SCLS-WS-08", "SCLS6-5", "SCLS6-7"],
    weeks: 8,
  },
  {
    id: "comp-f-t2",
    stage: "11-12 Science Life Skills",
    component: "Component F",
    term: 2,
    name: "Sustainable Living",
    description: "Students will manage their personal resources and contribute to sustainable practices, developing solutions for environmental problems.",
    outcomes: ["SCLS-RES-01", "SCLS-RES-02", "SCLS-WS-07", "SCLS6-6"],
    weeks: 8,
  },
  {
    id: "comp-f-t3",
    stage: "11-12 Science Life Skills",
    component: "Component F",
    term: 3,
    name: "Science in the Community",
    description: "Students will explore how scientific investigations and data are used in the community to solve problems and make decisions.",
    outcomes: ["SCLS-DAS-01", "SCLS-WS-08", "SCLS6-8", "SCLS6-9"],
    weeks: 8,
  },
  {
    id: "comp-f-t4",
    stage: "11-12 Science Life Skills",
    component: "Component F",
    term: 4,
    name: "My Scientific World",
    description: "Students will create a final project that synthesizes their scientific skills, from asking questions to communicating conclusions.",
    outcomes: ["SCLS-WS-02", "SCLS-WS-08", "SCLS6-1", "SCLS6-5", "SCLS6-7"],
    weeks: 8,
  },
];

// Combined export
export const allCurriculumUnits = [...k6Units, ...lifeSkillsUnits];
